### ISSUE TITLE
Unable to extract from Dell XPS 9560 Bios

### ISSUE THREAD

**Issue by wbushey** [coderobe/VBiosFinder#2]
I've attempted to extract the nVidia GPU BIOS from the following Dell XPS 9560 Bios update files with out success:
 - [1.5.0](http://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverId=WWT57&fileId=1963827075&osCode=WT64A&productCode=xps-15-9560-laptop&languageCode=it&categoryId=BI&lwp=rt)
 - [1.8.1](http://www.dell.com/support/home/us/en/19/Drivers/DriversDetails?driverId=7RVFJ)

In both cases I had innoextract, upx, 7z, and UEFIDump installed and available to vbiosfinder.

OS: Debian 9.4
Ruby: 2.5.0

```
./vbiosfinder extract ~/Downloads/XPS_15_9560_1.8.1.exe 
output will be stored in '/home/bill/Development/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes

trying to extract ./XPS_15_9560_1.8.1.exe
checking for innoextract... yes
not extractable with innoextract
checking for upx... yes
not extractable with upx
checking for 7z... yes
not extractable with 7z
checking for UEFIDump... yes
not an uefi image
Cleaning up garbage
```

**Comment by coderobe** [comment]
Oh yeah, I've taken a look at the BIOS of the XPS 9550 in the past, which i assume to be similar, and couldn't figure out how the update was packed. I doubt any laptop BIOS from the XPS family currently works, as they don't seem to employ the usual BIOS updater methods. If you have any information regarding their updater format i'd love to hear it.

**Comment by coderobe** [comment]
I've dug around a bit more and with https://github.com/coderobe/VBiosFinder/commit/ea89d34da221eace3b3aecbbb12709ac62c6e16c i'm able to extract uefi data from the dell updaters now, though it looks like either they're only partial uefi images (like some sort of delta update?) **or** my patch doesn't catch all the data, **or** they don't actually have the vbios in the uefi roms

**Comment by stzokev** [comment]
I'll post here, so I do not open new issue. I tried to extract from Dell Precision 7520 (https://downloads.dell.com/FOLDER05273023M/1/Precision_7x20_1.13.0.exe) but got nowhere:

`./vbiosfinder extract /Users/stefan.tsokev/Downloads/VBiosFinder-master/Precision_7x20_1.13.0.exe
output will be stored in '/Users/stefan.tsokev/Downloads/VBiosFinder-master/tmp-vbiosfinder'
checking for ruby... yes

checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./Precision_7x20_1.13.0.exe
found polyglot archive
trying to extract ./Precision_7x20_1.13.0.exe-polyglot
found polyglot archive
trying to extract ./Precision_7x20_1.13.0.exe-polyglot-polyglot
found zlib archive
trying to extract ./Precision_7x20_1.13.0.exe-polyglot-polyglot-zlib
found polyglot archive
trying to extract ./Precision_7x20_1.13.0.exe-polyglot-polyglot-zlib-polyglot
extracting uefi data
trying to extract ./Precision_7x20_1.13.0.exe
trying to extract ./Precision_7x20_1.13.0.exe-polyglot
trying to extract ./Precision_7x20_1.13.0.exe-polyglot-polyglot
trying to extract ./Precision_7x20_1.13.0.exe-polyglot-polyglot-zlib
trying to extract ./Precision_7x20_1.13.0.exe-polyglot-polyglot-zlib-polyglot
trying to extract ./mkmf.log
filtering for modules...
got 0 modules
finding vbios
no candidates found :(
Cleaning up garbage`

**Comment by stzokev** [comment]
@coderobe I tried on the [0] file inside the .exe and got further. Can you confirm that you get that as well:

```extracting uefi data
trying to extract ./[0]
found UEFIExtract archive
trying to extract ./[0]-polyglot
found UEFIExtract archive
trying to extract ./[0]-polyglot-zlib
trying to extract ./[0]-polyglot-zlib-polyglot
found UEFIExtract archive
trying to extract ./mkmf.log
found UEFIExtract archive
filtering for modules...
got 216 modules
finding vbios
no candidates found :(
input contains uefi data but no vbios could be found
the vbios might not be baked into the input!

**Comment by stzokev** [comment]
@coderobe If you could just confirm whether there is vbios in this https://downloads.dell.com/FOLDER05273023M/1/Precision_7x20_1.13.0.exe I would appreciate it.

**Comment by mani-rai** [comment]
Same for **XPS 9570** bios version: [1.12.0](https://downloads.dell.com/FOLDER05710631M/1/XPS_9570_1.12.0.exe?uid=bfd601db-4305-4f30-65cf-04b6766460fb&fn=XPS_9570_1.12.0.exe) as well. no candidates found :(

**Comment by T-vK** [comment]
Hello everyone, I found a way to unpack the BIOS update to the point that VBiosFinder was able to extract the vBIOS ROMs. 

Is there any chance we can add that functionality to VBiosFinder directly?

https://github.com/T-vK/DellBiosUnpackerPOC

Tested against this BIOS Update: https://dl.dell.com/FOLDER07188382M/1/XPS_15_9575_2-in-1_1.15.1.exe

Edit:
@wbushey @stzokev @mani-rai I just tested it against the BIOS updates you linked and it works as well.

**Comment by T-vK** [comment]
@coderobe I just noticed your thumbs-up. Can we talk about integrating this into VBiosFinder?

**Comment by coderobe** [comment]
yeah, sure - if you translate hdr-unpack to ruby i'll integrate it in here
i sadly don't currently have the time to look into that myself, but it looks like it should be fairly straightforward.

**Comment by T-vK** [comment]
Unfortunately I have no experience with Ruby at all. I'll see if I can figure it out though.

**Comment by T-vK** [comment]
@coderobe Okay, so I learned a bit of ruby now and ported the script: https://github.com/T-vK/DellBiosUnpackerPOC/blob/master/hdr-unpack.rb

Tested and works like a charm.

**Comment by coderobe** [comment]
alright - thanks! i'll look into merging it.

**Comment by T-vK** [comment]
I had a small bug in [unpack.sh](https://github.com/T-vK/DellBiosUnpackerPOC/blob/master/unpack.sh) that I just fixed. I accidentally wrote `ruby ./hdr-unpack.py "$BIOS_UPDATE_FILE"` instead of `ruby ./hdr-unpack.rb "$BIOS_UPDATE_FILE"`. (wrong file extension)

**Comment by ixil** [comment]
Just gave this a go on dell xps 9560, says it was successful :) thank @T-vK  and @coderobe

Took me a little bit to work out why I was getting this error message: (had not checked out the `new_engine` branch)
```
/home/ixil/dev/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)
	from /home/ixil/dev/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
	from /home/ixil/dev/VBiosFinder/src/extraction.rb:8:in `call'
	from /home/ixil/dev/VBiosFinder/src/extraction.rb:8:in `attempt'
	from /home/ixil/dev/VBiosFinder/src/methods.rb:46:in `block in run'
	from /home/ixil/dev/VBiosFinder/src/methods.rb:44:in `each'
	from /home/ixil/dev/VBiosFinder/src/methods.rb:44:in `run'
	from /home/ixil/dev/VBiosFinder/src/cli.rb:36:in `extract'
	from /home/ixil/dev/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/ixil/dev/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ixil/dev/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/ixil/dev/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from _init.rb:7:in `<main>'
```

**Comment by T-vK** [comment]
Btw @coderobe , any progress? :)

**Comment by Th3Guardian** [comment]
Hey, would you guys be able to extract from this one https://dl.dell.com/FOLDER07981163M/1/XPS_9570_1.23.0.exe and this one? https://dl.dell.com/FOLDER06224897M/1/XPS_9570_1.16.2.exe Thanks, much appreciated.

Since the nvbios is in the main bios, I don't suppose normal flashing with nvflash would work? Do I need to use an SPI programmer and sort of inject the "new" nvbios or edited nvbios into the current bios thus making a modded bios? If so, how would I go about flashing a modded bios on an XPS 9570? Will that even work?

Thanks for any help guys, and sorry if this is the wrong forum for it,

Thanks, kind regards,

David

**Comment by coderobe** [comment]
If you plan on flashing a modded bios, you're likely SOL there as you have no way of signing the updated package.

**Comment by T-vK** [comment]
I have modded BIOSes on non-Dell notebooks before and have been able to flash the resulting unsigned BIOSes using a hardware SPI flasher, but it involves opening the notebook and attaching a clamp to the SPI chip that stores the BIOS.

**Comment by Th3Guardian** [comment]
Yeah, and I would go about doing it with a CH341 programmer and an SOIC8 SOP8 Test Clip right? (Or whatever it's called).

Would this be the only way of getting an edited nvbios (or new) to the mainboard bios? Eg getting a 1050 Ti bios on the mainboard bios. Right now a Max Q bios is sitting on it, and I'm unsure if I can flash such a bios with nvflash, if it's sitting on the mainboard I mean. (Since reading with GPUz is not supported).

(But for a start, would you be able to extract the rom file from the 1.23 exe I provided? Thanks dude, really.)

**Comment by pixelplanetdev** [comment]
@T-vK your script works like a charm, thanks!

**Comment by Gak-den** [comment]
Hi there − so I've placed two copies of my DELL [BIOS update](https://dl.dell.com/FOLDER09885984M/1/G3_3579_3779_1.25.0.exe) in @T-vK's DellBiosUnpackerPOC script's installation directory as well as the VBiosFinder one, to no avail.
   VBiosFinder outputs the same result as @stzokev when trying to extract it from its install directory:

> VBiosFinder on  master [!?] via 💎 v3.4.7
❯ ./vbiosfinder extract ~/builds/3rdparty/VBiosFinder/G3_3579_3779_1.25.0.exe
/usr/lib/ruby/3.4.0/readline.rb:4: warning: reline was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add reline to your Gemfile or gemspec to silence this warning.
/home/Asterion/builds/3rdparty/VBiosFinder/src/cli.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
output will be stored in '/home/Asterion/builds/3rdparty/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes
checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./G3_3579_3779_1.25.0.exe
found polyglot archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot
found polyglot archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot-polyglot
found zlib archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot-polyglot-zlib
found polyglot archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot-polyglot-zlib-polyglot
extracting uefi data
trying to extract ./G3_3579_3779_1.25.0.exe
found UEFIExtract archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot
found UEFIExtract archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot-polyglot
found UEFIExtract archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot-polyglot-zlib
found UEFIExtract archive
trying to extract ./G3_3579_3779_1.25.0.exe-polyglot-polyglot-zlib-polyglot
found UEFIExtract archive
trying to extract ./mkmf.log
found UEFIExtract archive
filtering for modules...
got 815 modules
finding vbios
no candidates found :(
input contains uefi data but no vbios could be found
the vbios might not be baked into the input!
Cleaning up garbage

The /output directory only contains "bios_G3_3579_3779_1.25.0.exe".

DellBiosUnpackerPOC output after $ cd into it:

> ❯ ./unpack.sh G3_3579_3779_1.25.0.exe
<internal:/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require': cannot load such file -- hex_string (LoadError)
	from <internal:/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
	from ./hdr-unpack.rb:10:in 'main'
fatal: destination path 'PFSExtractor' already exists and is not an empty directory.
CMake Warning (dev) at CMakeLists.txt:1 (PROJECT):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/Asterion/builds/3rdparty/DellBiosUnpackerPOC/PFSExtractor
[100%] Built target PFSExtractor
Can't open input file
./unpack.sh: line 22: cd: G3_3579_3779_1.25.0.exe_decompressed.hdr.extracted: No such file or directory
#####################
#####################
#####################
Please adjust the path to your VBiosFinder installation otherwise the following will fail:
#####################
#####################
#####################
/usr/lib/ruby/3.4.0/readline.rb:4: warning: reline was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add reline to your Gemfile or gemspec to silence this warning.
/home/Asterion/builds/3rdparty/VBiosFinder/src/cli.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
output will be stored in '/home/Asterion/builds/3rdparty/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes
Cleaning up garbage
/usr/lib/ruby/3.4.0/fileutils.rb:2280:in 'File#initialize': No such file or directory @ rb_sysopen - /home/Asterion/builds/3rdparty/DellBiosUnpackerPOC/*.payload (Errno::ENOENT)
	from /usr/lib/ruby/3.4.0/fileutils.rb:2280:in 'IO.open'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2280:in 'FileUtils::Entry_#copy_file'
	from /usr/lib/ruby/3.4.0/fileutils.rb:1079:in 'FileUtils.copy_file'
	from /usr/lib/ruby/3.4.0/fileutils.rb:878:in 'block in FileUtils.cp'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2471:in 'block in FileUtils.fu_each_src_dest'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2485:in 'FileUtils.fu_each_src_dest0'
	from /usr/lib/ruby/3.4.0/fileutils.rb:2469:in 'FileUtils.fu_each_src_dest'
	from /usr/lib/ruby/3.4.0/fileutils.rb:877:in 'FileUtils.cp'
	from /home/Asterion/builds/3rdparty/VBiosFinder/src/cli.rb:34:in 'VBiosFinder::CLI#extract'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in 'Thor::Command#run'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in 'Thor::Invocation#invoke_command'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor.rb:387:in 'Thor.dispatch'
	from /home/Asterion/builds/3rdparty/VBiosFinder/vendor/bundle/ruby/3.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in 'Thor::Base::ClassMethods#start'
	from _init.rb:7:in 'main'

I'm on Arch Linux 6.17.9
Ruby 3.4.7
Bundler 4.0.0

What I did in my VBiosFinder installation before trying the DELL script in that order:
   - $ bundle config set build.posix-spawn --with-cflags=-Wno-incompatible-pointer-types
      ////(otherwise I would keep getting:
         "Installing posix-spawn 0.3.13 with native extensions
         Gem::Ext::BuildError: ERROR: Failed to build gem native extension."
      when running $ bundle update --bundler)
   - replaced "UEFIExtract" w/ "uefiextract" in src/extract-uefi.rb
      ////(I have built UEFIExtract with make prior to all of this)
   - edited "BUNDLED WITH" from "1.17.3" to "4.0.0" in the Gemfile.lock
   - $ bundle update --bundler
   - $ bundle config set path 'vendor/bundle'
   - $ /home/Asterion/.local/share/gem/ruby/3.4.0/gems/bundler-4.0.0/exe/bundle install
      ////(to install missing gems)
   - ./vbiosfinder extract ~/builds/3rdparty/VBiosFinder/G3_3579_3779_1.25.0.exe

Now, my question is the same as @stzokev: is it possible to determine if my GPU's video BIOS can be extracted from this most recent motherboard update?
   If not, how would I go about getting the unencrypted update directly from the board chip?

**Comment by Gak-den** [comment]
Side note, but any help would be very much appreciatedーVirt-manager outputs a message indicating that "Parameter 'x-pci-device-id' expects uint64"... I assume that my card cannot reliably be reset after booting/shutting down the VM, but there seems to be something else going on.

My system often freezes during the booting process into the host OS, and when I manage to reach a point where everything is loaded, sometimes the vfio_pci drivers may not fully bind the card to the VM and would still result in a lock up.
In both my host and guest OS, the card is detected as a generic 3D controller, though the vendor NVIDIA still shows up, and Device Manager shows "PCI\VEN_10DE&DEV_1C8C&SUBSYS_00000000&REV_A1", so I'm not sure if extracting a vBIOS would solve every problem.

    ❯ sudo dmesg | grep -i vfio
    [ 2.553048] VFIO - User Level meta-driver version: 0.3
    [ 2.695107] vfio_pci: add [10de:1c8c[ffffffff:ffffffff]] class 0x000000/00000000
    [ 4.222502] vfio_pci: add [10de:0fb9[ffffffff:ffffffff]] class 0x000000/00000000
    [ 216.060161] vfio-pci 0000:01:00.0: not ready 1023ms after resume; waiting
    [ 217.147997] vfio-pci 0000:01:00.0: not ready 2047ms after resume; waiting
    [ 219.260149] vfio-pci 0000:01:00.0: not ready 4095ms after resume; waiting
    [ 223.804082] vfio-pci 0000:01:00.0: not ready 8191ms after resume; waiting
    [ 232.508027] vfio-pci 0000:01:00.0: not ready 16383ms after resume; waiting
    [ 249.403758] vfio-pci 0000:01:00.0: not ready 32767ms after resume; waiting
    [ 283.707594] vfio-pci 0000:01:00.0: not ready 65535ms after resume; giving up

When I set these lines in the XML definition:

> <domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
     ...
     <devices>
         ...  
       <hostdev mode="subsystem" type="pci" managed="yes">
         <source>
           <address domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
         </source>
         <rom bar="on"/>
         <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0" multifunction="on"/>
       </hostdev>
         ...
     </devices>
         ...
     <qemu:override>
       <qemu:device alias="hostdev1">
         <qemu:frontend>
           <qemu:property name="romfile" type="string" value="~/GeForce_GTX_1050Ti_86-07-63-00-63.rom"/>
           <qemu:property name="x-pci-vendor-id" type="string" value="0x10de"/>
           <qemu:property name="x-pci-device-id" type="string" value="0x1c8c"/>
           <qemu:property name="x-pci-sub-vendor-id" type="string" value="0x1028"/>
           <qemu:property name="x-pci-sub-device-id" type="string" value="0x0870"/>
         </qemu:frontend>
       </qemu:device>
     </qemu:override>
   </domain>

Virt-manager either gives the aforementioned expected x-pci-device-id error, or...:

    Error starting domain: internal error: Unknown PCI header type '127' for device '0000:01:00:0'

I think I've read somewhere in the Arch wiki that the kernel itself may cause some issues with vfio_pci, probably a mix of factors with my particular laptop.
This particular error has also been reported on AMD platforms.
The current vBIOS I am using is one that I dumped directly from my dGPU. I've tried patching it on the edk2, which didn't make the dGPU show up as anything else than a 3D controller in the guest OS.

What I DIDN'T try:
   ---> Install proprietary NVIDIA drivers in my Linux host
