### ISSUE TITLE
Trying on P50 

### ISSUE THREAD

**Issue by colapsnux** [coderobe/VBiosFinder#35]
Trying on P50 without success.

Got this error **/opt/VBiosFinder-master/src/methods.rb:99:in `read': Is a directory @ io_fread - n1euj45w.exe.dump (Errno::EISDIR)**

Any ideas ? Thanks 

```
root@gu-ThinkPad-P50:/opt/VBiosFinder-master# ./vbiosfinder extract /home/gu/Downloads/n1euj45w.exe
output will be stored in '/opt/VBiosFinder-master/tmp-vbiosfinder'
checking for ruby... yes

checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./n1euj45w.exe
found zlib archive
wrong guess :(
found innoextract archive
Extracting "version 1.63-1.18 (N1EET90W-N1EHT38W)" - setup data version 5.5.7 (unicode)
 - "codeGetExtractPath/WINUPTP.EXE" - overwritten
 - "codeGetExtractPath/406E1.PAT"
 - "codeGetExtractPath/406E2.PAT"
 - "codeGetExtractPath/406E3.PAT"
 - "codeGetExtractPath/506E2.PAT"
 - "codeGetExtractPath/506E3.PAT"
 - "codeGetExtractPath/BCP.evs"
 - "codeGetExtractPath/BIOS_LOGO.TXT"
 - "codeGetExtractPath/BootX64.efi"
 - "codeGetExtractPath/chklogo.exe"
 - "codeGetExtractPath/chklogo.exe.config"
 - "codeGetExtractPath/DeleteFolder.xml"
 - "codeGetExtractPath/DeleteTasks.xml"
 - "codeGetExtractPath/Instruction JP - BIOS flash USB memory key.txt"
 - "codeGetExtractPath/Instruction US - BIOS flash USB memory key.txt"
 - "codeGetExtractPath/manifest.readme"
 - "codeGetExtractPath/mkusbkey.bat"
 - "codeGetExtractPath/SHELLFLASH.EFI"
 - "codeGetExtractPath/WinFlash32.exe"
 - "codeGetExtractPath/WinFlash32s.exe"
 - "codeGetExtractPath/WinFlash64.exe"
 - "codeGetExtractPath/WinFlash64s.exe"
 - "codeGetExtractPath/wininfo.exe"
 - "codeGetExtractPath/wininfo64.exe"
 - "codeGetExtractPath/WINUPTP.EXE"
 - "codeGetExtractPath/WINUPTP64.EXE"
 - "codeGetExtractPath/32bit/tpnflhlp.sys"
 - "codeGetExtractPath/64bit/tpnflhlp.sys"
 - "codeGetExtractPath/N1EET90W/$0AN1E00.FL1"
 - "codeGetExtractPath/N1EET90W/$0AN1E00.FL2"
 - "codeGetExtractPath/N1EET90W/CpuManifest.xml"
 - "codeGetExtractPath/N1EET90W/Manifest.xml"
Done.
trying to extract ./codeGetExtractPath/32bit/tpnflhlp.sys
trying to extract ./codeGetExtractPath/406E1.PAT
trying to extract ./codeGetExtractPath/406E2.PAT
trying to extract ./codeGetExtractPath/406E3.PAT
trying to extract ./codeGetExtractPath/506E2.PAT
trying to extract ./codeGetExtractPath/506E3.PAT
trying to extract ./codeGetExtractPath/64bit/tpnflhlp.sys
trying to extract ./codeGetExtractPath/BCP.evs
trying to extract ./codeGetExtractPath/BIOS_LOGO.TXT
trying to extract ./codeGetExtractPath/BootX64.efi
trying to extract ./codeGetExtractPath/DeleteFolder.xml
trying to extract ./codeGetExtractPath/DeleteTasks.xml
trying to extract ./codeGetExtractPath/Instruction JP - BIOS flash USB memory key.txt
trying to extract ./codeGetExtractPath/Instruction US - BIOS flash USB memory key.txt
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL1
found zlib archive
wrong guess :(
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL2
trying to extract ./codeGetExtractPath/N1EET90W/CpuManifest.xml
trying to extract ./codeGetExtractPath/N1EET90W/Manifest.xml
trying to extract ./codeGetExtractPath/SHELLFLASH.EFI
trying to extract ./codeGetExtractPath/WINUPTP.EXE
trying to extract ./codeGetExtractPath/WINUPTP64.EXE
trying to extract ./codeGetExtractPath/WinFlash32.exe
trying to extract ./codeGetExtractPath/WinFlash32s.exe
trying to extract ./codeGetExtractPath/WinFlash64.exe
trying to extract ./codeGetExtractPath/WinFlash64s.exe
trying to extract ./codeGetExtractPath/chklogo.exe
trying to extract ./codeGetExtractPath/chklogo.exe.config
trying to extract ./codeGetExtractPath/manifest.readme
trying to extract ./codeGetExtractPath/mkusbkey.bat
trying to extract ./codeGetExtractPath/wininfo.exe
trying to extract ./codeGetExtractPath/wininfo64.exe
extracting uefi data
trying to extract ./codeGetExtractPath/32bit/tpnflhlp.sys
found UEFIExtract archive
trying to extract ./codeGetExtractPath/406E1.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/406E2.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/406E3.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/506E2.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/506E3.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/64bit/tpnflhlp.sys
found UEFIExtract archive
trying to extract ./codeGetExtractPath/BCP.evs
found UEFIExtract archive
trying to extract ./codeGetExtractPath/BIOS_LOGO.TXT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/BootX64.efi
found UEFIExtract archive
trying to extract ./codeGetExtractPath/DeleteFolder.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/DeleteTasks.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/Instruction JP - BIOS flash USB memory key.txt
found UEFIExtract archive
trying to extract ./codeGetExtractPath/Instruction US - BIOS flash USB memory key.txt
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL1
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL2
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/CpuManifest.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/Manifest.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/SHELLFLASH.EFI
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WINUPTP.EXE
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WINUPTP64.EXE
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash32.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash32s.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash64.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash64s.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/chklogo.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/chklogo.exe.config
found UEFIExtract archive
trying to extract ./codeGetExtractPath/manifest.readme
found UEFIExtract archive
trying to extract ./codeGetExtractPath/mkusbkey.bat
found UEFIExtract archive
trying to extract ./codeGetExtractPath/wininfo.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/wininfo64.exe
found UEFIExtract archive
trying to extract ./mkmf.log
found UEFIExtract archive
trying to extract ./n1euj45w.exe
found UEFIExtract archive
filtering for modules...
got 5417 modules
finding vbios
7 possible candidates
checking for rom-parser... yes
Found VBIOS for device 8086:0406!
Cleaning up garbage
Traceback (most recent call last):
	12: from _init.rb:7:in `<main>'
	11: from /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
	10: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	 9: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	 8: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	 7: from /opt/VBiosFinder-master/src/cli.rb:36:in `extract'
	 6: from /opt/VBiosFinder-master/src/methods.rb:61:in `run'
	 5: from /opt/VBiosFinder-master/src/methods.rb:61:in `each'
	 4: from /opt/VBiosFinder-master/src/methods.rb:69:in `block in run'
	 3: from /opt/VBiosFinder-master/src/methods.rb:98:in `check_cpy'
	 2: from /opt/VBiosFinder-master/src/methods.rb:98:in `each'
	 1: from /opt/VBiosFinder-master/src/methods.rb:99:in `block in check_cpy'
/opt/VBiosFinder-master/src/methods.rb:99:in `read': Is a directory @ io_fread - n1euj45w.exe.dump (Errno::EISDIR)
```

**Comment by coderobe** [comment]
I think this may be fixed with https://github.com/coderobe/VBiosFinder/commit/88aea3ae66ad676ef3f97af62c952424c47bd15a - can you pull the latest version and try again?

**Comment by colapsnux** [comment]
@coderobe  [88ae3a](https://github.com/coderobe/VBiosFinder/commit/88aea3ae66ad676ef3f97af62c952424c47bd15a) worked like a charm ! Thanks you for your quick feedback, really appreciate it.

```
[gu@gu-ThinkPad-P50:/opt/VBiosFinder-master$ ./vbiosfinder extract /home/gu/Downloads/n1euj45w.exe 
output will be stored in '/opt/VBiosFinder-master/tmp-vbiosfinder'
checking for ruby... yes

checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./n1euj45w.exe
found zlib archive
wrong guess :(
found innoextract archive
Extracting "version 1.63-1.18 (N1EET90W-N1EHT38W)" - setup data version 5.5.7 (unicode)
 - "codeGetExtractPath/WINUPTP.EXE" - overwritten
 - "codeGetExtractPath/406E1.PAT"
 - "codeGetExtractPath/406E2.PAT"
 - "codeGetExtractPath/406E3.PAT"
 - "codeGetExtractPath/506E2.PAT"
 - "codeGetExtractPath/506E3.PAT"
 - "codeGetExtractPath/BCP.evs"
 - "codeGetExtractPath/BIOS_LOGO.TXT"
 - "codeGetExtractPath/BootX64.efi"
 - "codeGetExtractPath/chklogo.exe"
 - "codeGetExtractPath/chklogo.exe.config"
 - "codeGetExtractPath/DeleteFolder.xml"
 - "codeGetExtractPath/DeleteTasks.xml"
 - "codeGetExtractPath/Instruction JP - BIOS flash USB memory key.txt"
 - "codeGetExtractPath/Instruction US - BIOS flash USB memory key.txt"
 - "codeGetExtractPath/manifest.readme"
 - "codeGetExtractPath/mkusbkey.bat"
 - "codeGetExtractPath/SHELLFLASH.EFI"
 - "codeGetExtractPath/WinFlash32.exe"
 - "codeGetExtractPath/WinFlash32s.exe"
 - "codeGetExtractPath/WinFlash64.exe"
 - "codeGetExtractPath/WinFlash64s.exe"
 - "codeGetExtractPath/wininfo.exe"
 - "codeGetExtractPath/wininfo64.exe"
 - "codeGetExtractPath/WINUPTP.EXE"
 - "codeGetExtractPath/WINUPTP64.EXE"
 - "codeGetExtractPath/32bit/tpnflhlp.sys"
 - "codeGetExtractPath/64bit/tpnflhlp.sys"
 - "codeGetExtractPath/N1EET90W/$0AN1E00.FL1"
 - "codeGetExtractPath/N1EET90W/$0AN1E00.FL2"
 - "codeGetExtractPath/N1EET90W/CpuManifest.xml"
 - "codeGetExtractPath/N1EET90W/Manifest.xml"
Done.
trying to extract ./codeGetExtractPath/32bit/tpnflhlp.sys
trying to extract ./codeGetExtractPath/406E1.PAT
trying to extract ./codeGetExtractPath/406E2.PAT
trying to extract ./codeGetExtractPath/406E3.PAT
trying to extract ./codeGetExtractPath/506E2.PAT
trying to extract ./codeGetExtractPath/506E3.PAT
trying to extract ./codeGetExtractPath/64bit/tpnflhlp.sys
trying to extract ./codeGetExtractPath/BCP.evs
trying to extract ./codeGetExtractPath/BIOS_LOGO.TXT
trying to extract ./codeGetExtractPath/BootX64.efi
trying to extract ./codeGetExtractPath/DeleteFolder.xml
trying to extract ./codeGetExtractPath/DeleteTasks.xml
trying to extract ./codeGetExtractPath/Instruction JP - BIOS flash USB memory key.txt
trying to extract ./codeGetExtractPath/Instruction US - BIOS flash USB memory key.txt
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL1
found zlib archive
wrong guess :(
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL2
trying to extract ./codeGetExtractPath/N1EET90W/CpuManifest.xml
trying to extract ./codeGetExtractPath/N1EET90W/Manifest.xml
trying to extract ./codeGetExtractPath/SHELLFLASH.EFI
trying to extract ./codeGetExtractPath/WINUPTP.EXE
trying to extract ./codeGetExtractPath/WINUPTP64.EXE
trying to extract ./codeGetExtractPath/WinFlash32.exe
trying to extract ./codeGetExtractPath/WinFlash32s.exe
trying to extract ./codeGetExtractPath/WinFlash64.exe
trying to extract ./codeGetExtractPath/WinFlash64s.exe
trying to extract ./codeGetExtractPath/chklogo.exe
trying to extract ./codeGetExtractPath/chklogo.exe.config
trying to extract ./codeGetExtractPath/manifest.readme
trying to extract ./codeGetExtractPath/mkusbkey.bat
trying to extract ./codeGetExtractPath/wininfo.exe
trying to extract ./codeGetExtractPath/wininfo64.exe
extracting uefi data
trying to extract ./codeGetExtractPath/32bit/tpnflhlp.sys
found UEFIExtract archive
trying to extract ./codeGetExtractPath/406E1.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/406E2.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/406E3.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/506E2.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/506E3.PAT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/64bit/tpnflhlp.sys
found UEFIExtract archive
trying to extract ./codeGetExtractPath/BCP.evs
found UEFIExtract archive
trying to extract ./codeGetExtractPath/BIOS_LOGO.TXT
found UEFIExtract archive
trying to extract ./codeGetExtractPath/BootX64.efi
found UEFIExtract archive
trying to extract ./codeGetExtractPath/DeleteFolder.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/DeleteTasks.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/Instruction JP - BIOS flash USB memory key.txt
found UEFIExtract archive
trying to extract ./codeGetExtractPath/Instruction US - BIOS flash USB memory key.txt
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL1
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/$0AN1E00.FL2
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/CpuManifest.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/N1EET90W/Manifest.xml
found UEFIExtract archive
trying to extract ./codeGetExtractPath/SHELLFLASH.EFI
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WINUPTP.EXE
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WINUPTP64.EXE
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash32.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash32s.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash64.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/WinFlash64s.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/chklogo.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/chklogo.exe.config
found UEFIExtract archive
trying to extract ./codeGetExtractPath/manifest.readme
found UEFIExtract archive
trying to extract ./codeGetExtractPath/mkusbkey.bat
found UEFIExtract archive
trying to extract ./codeGetExtractPath/wininfo.exe
found UEFIExtract archive
trying to extract ./codeGetExtractPath/wininfo64.exe
found UEFIExtract archive
trying to extract ./mkmf.log
found UEFIExtract archive
trying to extract ./n1euj45w.exe
found UEFIExtract archive
filtering for modules...
got 5417 modules
finding vbios
7 possible candidates
checking for rom-parser... yes
Found VBIOS for device 8086:0406!
Found VBIOS for device 10de:13b0!
Found VBIOS for device 10de:13b0!
Found VBIOS for device 10de:13b1!
Found VBIOS for device 10de:13b1!
Found VBIOS for device 10de:1348!
Found VBIOS for device 10de:1349!
Job done. Extracted files can be found in /opt/VBiosFinder-master/tmp-vbiosfinder/../output
Cleaning up garbage
gu@gu-ThinkPad-P50:/opt/VBiosFinder-master$ ll output/
total 8856
drwxr-xr-x 2 gu gu    4096 févr. 15 08:40 ./
drwxr-xr-x 8 gu gu    4096 févr. 15 08:40 ../
-rwxr-xr-x 1 gu gu 8700384 févr. 15 08:39 bios_n1euj45w.exe*
-rw-rw-r-- 1 gu gu   37888 févr. 15 08:40 vbios_10de_1348_1.rom
-rw-rw-r-- 1 gu gu   36352 févr. 15 08:40 vbios_10de_1349_1.rom
-rw-rw-r-- 1 gu gu  104448 févr. 15 08:40 vbios_10de_13b0_1.rom
-rw-rw-r-- 1 gu gu  104448 févr. 15 08:40 vbios_10de_13b1_1.rom
-rw-rw-r-- 1 gu gu   65536 févr. 15 08:40 vbios_8086_0406_1.rom
gu@gu-ThinkPad-P50:/opt/VBiosFinder-master$ 
```
