### ISSUE TITLE
No such file or directory @ rb_sysopen - 8auj30us.exe (Errno::ENOENT)

### ISSUE THREAD

**Issue by rajeshmanivan** [coderobe/VBiosFinder#37]
Facing this error, tried it in 2 different distros.
May be something to do with the new ruby.

naan@clrhost ~/Source_Installs/VBiosFinder $  ./vbiosfinder extract 8auj30us.exe 
output will be stored in '/home/naan/Source_Installs/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes
Cleaning up garbage
/usr/lib64/ruby/3.0.0/fileutils.rb:1414:in `initialize': No such file or directory @ rb_sysopen - 8auj30us.exe (Errno::ENOENT)
        from /usr/lib64/ruby/3.0.0/fileutils.rb:1414:in `open'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:1414:in `copy_file'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:514:in `copy_file'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:433:in `block in cp'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:1611:in `fu_each_src_dest0'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /usr/lib64/ruby/3.0.0/fileutils.rb:432:in `cp'
        from /home/naan/Source_Installs/VBiosFinder/src/cli.rb:34:in `extract'
        from /home/naan/Source_Installs/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /home/naan/Source_Installs/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/naan/Source_Installs/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /home/naan/Source_Installs/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from _init.rb:7:in `<main>'

**Comment by frossu** [comment]
Faced the same issue. Using absolute path worked, as it was mentioned in #10

**Comment by p1xxxel** [comment]
you need to enter the full path to the exe
