### ISSUE TITLE
Cocaine::CommandNotFoundError

### ISSUE THREAD

**Issue by DerMauch** [coderobe/VBiosFinder#4]
Crashed with the following output:

```
[mauch@M80 VBiosFinder]$ ./vbiosfinder extract /home/mauch/mx150rom/n22uj05w.exe
output will be stored in '/home/mauch/mx150rom/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes

trying to extract ./n22uj05w.exe
checking for innoextract... yes
Cleaning up garbage
Traceback (most recent call last):
12: from _init.rb:7:in `<main>'
11: from /home/mauch/mx150rom/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
10: from /home/mauch/mx150rom/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
9: from /home/mauch/mx150rom/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
8: from /home/mauch/mx150rom/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
7: from /home/mauch/mx150rom/VBiosFinder/src/cli.rb:32:in `extract'
6: from /home/mauch/mx150rom/VBiosFinder/src/methods.rb:20:in `run'
5: from /home/mauch/mx150rom/VBiosFinder/src/methods.rb:20:in `each'
4: from /home/mauch/mx150rom/VBiosFinder/src/methods.rb:20:in `block in run'
3: from /home/mauch/mx150rom/VBiosFinder/src/extraction.rb:8:in `attempt'
2: from /home/mauch/mx150rom/VBiosFinder/src/extraction.rb:8:in `call'
1: from /home/mauch/mx150rom/VBiosFinder/src/extract-innosetup.rb:19:in `innosetup'
/home/mauch/mx150rom/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:82:in `run': Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError)
```

- Arch Linux x86_64
- ruby 2.5.1p57
- rom-fixer, rom-parser, UEFITool placed in ./3rdparty
- Lenovo Thinkpad T480s (NVIDIA MX150)
- BIOS Update 1.12 (n22uj05w.exe)

**Comment by coderobe** [comment]
Do you have a working innoextract installed? [ruby's find_executable](https://apidock.com/ruby/Object/find_executable) is able to find it, but further on it can't be ran because it's **not** found in your PATH.
Is your $PATH unset or bad by any chance?

**Comment by DerMauch** [comment]
Hi again, sorry for opening this issue hastily. I was dumb enough to install innoextract without updating the rest of Arch Linux which caused it to not find libraries like libboost.
VBiosFinder ran perfectly and found the vBIOS for both Intel UHD 620 and NVIDIA MX150 on my Thinkpad T480s. :)

**Comment by coderobe** [comment]
Congratulations, you just voided your Arch Linux warranty :tm: - partial updates are explicitly unsupported.

https://gist.github.com/vodik/5660494
