### ISSUE TITLE
I tried to extract but i get this error.

### ISSUE THREAD

**Issue by GRNHACKER** [coderobe/VBiosFinder#40]
./vbiosfinder extract /home/greenhacker/Downloads/ASUS_X512FL_309_BIOS_Update.exe
output will be stored in '/home/greenhacker/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes

checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./ASUS_X512FL_309_BIOS_Update.exe
found innoextract archive
Extracting "ASUS X512FL BIOS" - setup data version 6.0.0 (unicode)
 - "tmp/ASUS_X512FL_309_BIOS_Update/AsusBusinessIntelligenceCPlusLib.dll" [temp]
 - "tmp/ASUS_X512FL_309_BIOS_Update/AsusInstallerBI.exe" [temp]
 - "tmp/ASUS_X512FL_309_BIOS_Update/BusinessIntelligenceCPlusLib.dll" [temp]
 - "tmp/ASUS_X512FL_309_BIOS_Update/README.txt" [temp]
 - "app/Install.bat" [temp]
 - "app/pnputil.exe" [temp]
 - "app/X512FL.309" [temp]
 - "app/x512fl_309.cat" [temp]
 - "app/X512FL_309.inf" [temp]
 - "app/License.txt" [temp]
Done with 1 warning.
trying to extract ./app/Install.bat
trying to extract ./app/License.txt
trying to extract ./app/X512FL.309
trying to extract ./app/X512FL_309.inf
trying to extract ./app/pnputil.exe
trying to extract ./app/x512fl_309.cat
trying to extract ./tmp/ASUS_X512FL_309_BIOS_Update/AsusBusinessIntelligenceCPlusLib.dll
trying to extract ./tmp/ASUS_X512FL_309_BIOS_Update/AsusInstallerBI.exe
trying to extract ./tmp/ASUS_X512FL_309_BIOS_Update/BusinessIntelligenceCPlusLib.dll
trying to extract ./tmp/ASUS_X512FL_309_BIOS_Update/README.txt
extracting uefi data
trying to extract ./ASUS_X512FL_309_BIOS_Update.exe
Cleaning up garbage
/home/greenhacker/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)
	from /home/greenhacker/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
	from /home/greenhacker/VBiosFinder/src/extraction.rb:8:in `call'
	from /home/greenhacker/VBiosFinder/src/extraction.rb:8:in `attempt'
	from /home/greenhacker/VBiosFinder/src/methods.rb:46:in `block in run'
	from /home/greenhacker/VBiosFinder/src/methods.rb:44:in `each'
	from /home/greenhacker/VBiosFinder/src/methods.rb:44:in `run'
	from /home/greenhacker/VBiosFinder/src/cli.rb:36:in `extract'
	from /home/greenhacker/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/greenhacker/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/greenhacker/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/greenhacker/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from _init.rb:7:in `<main>'

**Comment by coderobe** [comment]
did you set up uefiextract correctly?
