### ISSUE TITLE
solution for Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)

### ISSUE THREAD

**Issue by demlak** [coderobe/VBiosFinder#50]
the name of tool UEFIExtract needs to be case-sensitive!

i was using arch linux with uefitool.. but i always run into this error:

```
.../VBiosFinder/vendor/bundle/ruby/3.0.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)
	from /home/demlak/lala/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
	from /home/demlak/lala/VBiosFinder/src/extraction.rb:8:in `call'
	from /home/demlak/lala/VBiosFinder/src/extraction.rb:8:in `attempt'
	from /home/demlak/lala/VBiosFinder/src/methods.rb:46:in `block in run'
	from /home/demlak/lala/VBiosFinder/src/methods.rb:44:in `each'
	from /home/demlak/lala/VBiosFinder/src/methods.rb:44:in `run'
	from /home/demlak/lala/VBiosFinder/src/cli.rb:36:in `extract'
	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from _init.rb:7:in `<main>'
```

solution: copy `/usr/bin/uefiextract` to folder `3rdparty` and rename it to `UEFIExtract`

and yes.. `/usr/bin` is in path
and no, it's not working by just copy into `3rdparty`, you HAVE TO rename it.

p.s. thx for creating this tool..

**Comment by vkhodygo** [comment]
Funny thing, I got my hands on the code only yesterday and spent all that time looking for the problem instead of reading your issue.

Anyway, see #51

**Comment by KyleSebion** [comment]
> the name of tool UEFIExtract needs to be case-sensitive!
> 
> i was using arch linux with uefitool.. but i always run into this error:
> 
> ```
> .../VBiosFinder/vendor/bundle/ruby/3.0.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)
> 	from /home/demlak/lala/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
> 	from /home/demlak/lala/VBiosFinder/src/extraction.rb:8:in `call'
> 	from /home/demlak/lala/VBiosFinder/src/extraction.rb:8:in `attempt'
> 	from /home/demlak/lala/VBiosFinder/src/methods.rb:46:in `block in run'
> 	from /home/demlak/lala/VBiosFinder/src/methods.rb:44:in `each'
> 	from /home/demlak/lala/VBiosFinder/src/methods.rb:44:in `run'
> 	from /home/demlak/lala/VBiosFinder/src/cli.rb:36:in `extract'
> 	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> 	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> 	from /home/demlak/lala/VBiosFinder/vendor/bundle/ruby/3.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
> 	from _init.rb:7:in `<main>'
> ```
> 
> solution: copy `/usr/bin/uefiextract` to folder `3rdparty` and rename it to `UEFIExtract`
> 
> and yes.. `/usr/bin` is in path and no, it's not working by just copy into `3rdparty`, you HAVE TO rename it.
> 
> p.s. thx for creating this tool..

Ran into this today. Thanks for the fix and tool! Seems to work OK with lenovo bios update for IdeaPad Gaming 3 15ACH6.
