### ISSUE TITLE
error to install

### ISSUE THREAD

**Issue by segator** [coderobe/VBiosFinder#54]
```/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:272:in `search_up': undefined method `untaint' for "/data/VBiosFinder":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:259:in `find_file'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:251:in `find_gemfile'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:27:in `root'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler.rb:234:in `root'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler.rb:244:in `app_config_path'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler.rb:273:in `settings'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:97:in `<class:CLI>'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:7:in `<module:Bundler>'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:6:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:23:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'```

**Comment by slalomnut** [comment]
bump

**Comment by MykeHalk** [comment]
update your bundler with the command (bundle update --bundler)
