### ISSUE TITLE
Archlinux: posix-spawn requirement breaks build

### ISSUE THREAD

**Issue by ilikenwf** [coderobe/VBiosFinder#59]
Removing the Gemfile.lock and removing posix-spawn from the Gemfile results in successful build and run but actually running after does not work...so something's amiss.

ruby 3.2.4-1.1
ruby-bundler 2.5.11-2
rubygems 3.4.19-1

```

./vbiosfinder extract gluj44us.exe                                                                [08/27 05:13 PM]
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
output will be stored in '/home/me/repos/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes
Cleaning up garbage
/usr/lib/ruby/3.2.0/fileutils.rb:2290:in `initialize': No such file or directory @ rb_sysopen - gluj44us.exe (Errno::ENOENT)
	from /usr/lib/ruby/3.2.0/fileutils.rb:2290:in `open'
	from /usr/lib/ruby/3.2.0/fileutils.rb:2290:in `copy_file'
	from /usr/lib/ruby/3.2.0/fileutils.rb:1088:in `copy_file'
	from /usr/lib/ruby/3.2.0/fileutils.rb:887:in `block in cp'
	from /usr/lib/ruby/3.2.0/fileutils.rb:2481:in `block in fu_each_src_dest'
	from /usr/lib/ruby/3.2.0/fileutils.rb:2495:in `fu_each_src_dest0'
	from /usr/lib/ruby/3.2.0/fileutils.rb:2479:in `fu_each_src_dest'
	from /usr/lib/ruby/3.2.0/fileutils.rb:886:in `cp'
	from /home/matt/repos/VBiosFinder/src/cli.rb:34:in `extract'
	from /home/matt/repos/VBiosFinder/vendor/bundle/ruby/3.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/matt/repos/VBiosFinder/vendor/bundle/ruby/3.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/matt/repos/VBiosFinder/vendor/bundle/ruby/3.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/matt/repos/VBiosFinder/vendor/bundle/ruby/3.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from _init.rb:7:in `<main>'

```

**Comment by KolibroidAmy** [comment]
Also on arch here. I'm not very familiar with ruby but it seems like posix-spawn is abandoned and now causes a warning on modern compilers, which makes the install fail. I was able to avoid it by silencing the warning using `bundle config build.posix-spawn --with-cflags="-Wno-incompatible-pointer-types"`.

For future reference though, I did also have to update the bundler version in the lock file, and replace `"UEFIExtract"` with `"uefiextract"` in src/extract-eufi.rb, since the uefitool-bin AUR package only provides a lower case version. But I can confirm that it has successfully extracted the VBIOS-s for my Acer PH315-51!

**Comment by ilikenwf** [comment]
> Also on arch here. I'm not very familiar with ruby but it seems like posix-spawn is abandoned and now causes a warning on modern compilers, which makes the install fail. I was able to avoid it by silencing the warning using `bundle config build.posix-spawn --with-cflags="-Wno-incompatible-pointer-types"`.
> 
> For future reference though, I did also have to update the bundler version in the lock file, and replace `"UEFIExtract"` with `"uefiextract"` in src/extract-eufi.rb, since the uefitool-bin AUR package only provides a lower case version. But I can confirm that it has successfully extracted the VBIOS-s for my Acer PH315-51!

Nice! You should consider making it a PKGBUILD and tossing it on the AUR sometime. Great work!

**Comment by nicbn** [comment]
> `bundle config build.posix-spawn --with-cflags="-Wno-incompatible-pointer-types"`

This fixed the build on Fedora as well. Thanks!
