### ISSUE TITLE
Undefined method "untaint"

### ISSUE THREAD

**Issue by SamuraiDestroy** [coderobe/VBiosFinder#60]
When attempting to extract the VBIOS from the latest ASUS TUF A15 FA507NV BIOS update exe, it returns the following error:
`/home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:272:in `search_up': undefined method `untaint' for "/home/SamuraiDestroy/Downloads/VBiosFinder-master":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:259:in `find_file'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:251:in `find_gemfile'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:27:in `root'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:234:in `root'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:246:in `app_config_path'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:273:in `settings'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/feature_flag.rb:21:in `block in settings_method'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/cli.rb:97:in `<class:CLI>'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/cli.rb:7:in `<module:Bundler>'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/cli.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/exe/bundle:23:in `block in <top (required)>'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
	from /usr/bin/bundle:25:in `load'
	from /usr/bin/bundle:25:in `<main>'
`

**Comment by sechmachine727** [comment]
This error occurs because the untaint method has been removed in Ruby 3.3.0, and Bundler 1.17.3 is trying to use it. To fix this, you'll need to update Bundler to a version compatible with Ruby 3.3.01. Here’s how you can do it:

Update RubyGems: Ensure RubyGems is up to date:
`gem update --system`

Install Bundler: Install or update Bundler to a version compatible with Ruby 3.3.0:
`gem install bundler`

Update Bundler: Update your project's Bundler version:
`bundle update --bundler`

Run Bundle Install: Finally, run bundle install again:
`bundle install --path=vendor/bundle`

This should resolve the issue. Does this help?

**Comment by SamuraiDestroy** [comment]
`gem update --system` didn't work but everything else did just fine. I ran VBIOSFinder again and now the error is
`checking for ruby... yes

checking for innoextract... yes
checking for upx... no
Install 'upx' on your system (required for UPX executables)
checking for 7z... yes
trying to extract ./ASUS_FA507NV_314_BIOS_Update.exe
found zlib archive
wrong guess :(
found 7z archive
trying to extract ./BIOSInstall.ps1
trying to extract ./Cabfile/FA507NV.314
found zlib archive
wrong guess :(
trying to extract ./Cabfile/FA507NV_314.inf
trying to extract ./Cabfile/fa507nv_314.cat
trying to extract ./Install.bat
extracting uefi data
trying to extract ./ASUS_FA507NV_314_BIOS_Update.exe
Cleaning up garbage
/home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/extract-uefi.rb:20:in `uefi'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/extraction.rb:8:in `call'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/extraction.rb:8:in `attempt'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/methods.rb:46:in `block in run'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/methods.rb:44:in `each'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/methods.rb:44:in `run'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/src/cli.rb:36:in `extract'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/SamuraiDestroy/Downloads/VBiosFinder-master/vendor/bundle/ruby/3.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from _init.rb:7:in `<main>'`
I'm assuming I don't need UPX since it's an .exe file and anyway I had trouble trying to install it.

**Comment by sechmachine727** [comment]
I could send you an upx executable, but it might be worth checking out this: https://github.com/coderobe/VBiosFinder/pull/56

**Comment by SamuraiDestroy** [comment]
I don't really understand #50 since it says /usr/bin/uefiextract but I don't have that. Is it somewhere inside of UEFITool?

**Comment by sechmachine727** [comment]
> I don't really understand #50 since it says /usr/bin/uefiextract but I don't have that. Is it somewhere inside of UEFITool?

UEFITool Repo has UEFIExtract, a separate executable. But named uefiextract (lowercase) by default. Since Linux is case sensitive so you have to rename it. But first made sure you put UEFIExtract executable in 3rdparty dir.

**Comment by SamuraiDestroy** [comment]
I can't find the UEFIExtract executable, where is it?

**Comment by sechmachine727** [comment]
> I can't find the UEFIExtract executable, where is it?

Should be in this zip: 
https://objects.githubusercontent.com/github-production-release-asset-2e65be/13405986/30ef6ef1-b34c-4338-b795-bd7bcc4a824b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241106%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241106T114556Z&X-Amz-Expires=300&X-Amz-Signature=f99a4699b1cbecac4d36a6172b9a15c8645ebd853c489d18e03b1b97845c8b4f&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3DUEFIExtract_NE_A68_x64_linux.zip&response-content-type=application%2Foctet-stream

**Comment by SamuraiDestroy** [comment]
That link just leads to a blank page.
Edit: I found the executable on the UEFITool page, going to try it again now
Edit 2: It works now! It output an exe file and a bin file though, is that supposed to happen? 
Edit 3 (This is kind of getting stupid): So I'm trying to get the ROM for [this](https://gitlab.com/risingprismtv/single-gpu-passthrough/-/wikis/6-Preparation-and-placing-of-the-ROM-file#dumping-your-gpu-rom) since NVflash didn't work properly and it says there's supposed to be text somewhere under char that says "VIDEO" but ctrl+f says it doesnt have it. I checked both the exe and the bin file.

**Comment by sechmachine727** [comment]
Can you give me the rom file, see if I could extract it? This tool depends on luck tho. Did not extract the vbios ROM from my old laptop either (Acer Nitro 5 AN515-52 2018)
