### ISSUE TITLE
command not found error trying to read an Acer BIOS

### ISSUE THREAD

**Issue by exodist** [coderobe/VBiosFinder#8]
```
upx: ./A4DBH119.exe: IOException: upx-./A4DBH119.exe: No such file or directory
found 7z archive
trying to extract ./Ding.wav
trying to extract ./FWUpdLcl.exe
trying to extract ./FlsHook.exe
trying to extract ./FlsHookDll.dll
trying to extract ./H2OFFT-W.exe
trying to extract ./Vpro.fd
trying to extract ./iscflash.dll
trying to extract ./iscflash.sys
trying to extract ./iscflashx64.sys
trying to extract ./platform.ini
trying to extract ./xerces-c_2_7.dll
extracting uefi data
trying to extract ./A4DBH119.exe
Cleaning up garbage
Traceback (most recent call last):
        12: from _init.rb:7:in `<main>'
        11: from /home/exodist/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        10: from /home/exodist/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         9: from /home/exodist/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         8: from /home/exodist/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         7: from /home/exodist/VBiosFinder/src/cli.rb:36:in `extract'
         6: from /home/exodist/VBiosFinder/src/methods.rb:43:in `run'
         5: from /home/exodist/VBiosFinder/src/methods.rb:43:in `each'
         4: from /home/exodist/VBiosFinder/src/methods.rb:45:in `block in run'
         3: from /home/exodist/VBiosFinder/src/extraction.rb:8:in `attempt'
         2: from /home/exodist/VBiosFinder/src/extraction.rb:8:in `call'
         1: from /home/exodist/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
/home/exodist/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:82:in `run': Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError)
```

**Comment by exodist** [comment]
This is probably me not getting UEFIExtract into 3rd-party, will close if that turns out to be the case.

**Comment by exodist** [comment]
yes, my bad.
